### ISSUE TITLE
ナビゲーションバーの項目追加提案

### ISSUE THREAD

**Issue by fightingnemo** [isoc-jp/website#3]
ナビゲーションバーにWikiの「[News Letter](https://www.isoc.jp/wiki.cgi?page=NewsLetter)」に相当する項目がないため，「News Letter」追加をお願いします．

**Comment by tanupoo** [comment]
https://github.com/isoc-jp/website/pull/55 にて対応中です。

**Comment by tanupoo** [comment]
対応しました。
