### ISSUE TITLE
ISOC-JPへの参加方法へのリンクを張りたい。

### ISSUE THREAD

**Issue by taiji-k** [isoc-jp/website#41]
Home にある「参加方法」にリンクが貼られていないので。

以下のリンクでOK？新しいページで作ってもOKかと。

ISOC-JP への登録方法 / How to register
https://www-old.isoc.jp/wiki.cgi?page=How%5Fto%5Fjoin%5FISOC%2DJP

**Comment by h-shiozawa** [comment]
8/23 のWebメンテナンス作業で、作業済み
https://isoc.jp/joinus/　にリンクを貼りました
