### ISSUE TITLE
ISOC-JP発足の認定証へのリンクが切れている。

### ISSUE THREAD

**Issue by tanupoo** [isoc-jp/website#74]
# WHAT
https://www.isoc.jp/aboutus/
*1994年8月 ISOC-JP 発足 ([当時の認定証 Original Certificate](https://www.isoc.jp/aboutus/materials/ISOC-JP-Chapter-Certificate.pdf)) / August 1994: ISOC-JP launched*
のリンクが切れている。

# WHY
リンクが切れている。

# URL
https://www.isoc.jp/aboutus/

**Comment by h-shiozawa** [comment]
Google Drive に認定証アップロード & リンク修正済み
