### ISSUE TITLE
2022 AGM告知記事掲載

### ISSUE THREAD

**Issue by toshiotachibana** [isoc-jp/website#82]
2022/12/13開催のAGMの告知記事を掲載する。
現時点での内容は [Members 9] [Members 12]で告知した内容のみとし、参加登録方法については準備整い次第アップデートするものとする。
Markdown記法での文案は次の場所に置く。
https://drive.google.com/file/d/13lCRucEDwOgEOovYk_GWnOXKm5jXCN_d/view?usp=sharing

**Comment by sylph01** [comment]
https://isoc.jp/activities/2022agm-announcement/ にて更新済みにつきcloseします。
